/**
 * Batched core-Lean file generator for symspec's `certify` tier (AC-5-1).
 *
 * Emits exactly ONE self-contained `.lean` source file for an entire spec:
 * every theorem the certify pipeline wants to check is batched into a single
 * file so the ~0.4s per-process Lean startup cost (research-lean4.md §1.2) is
 * paid once for the whole run instead of once per requirement pair.
 *
 * Import surface is intentionally minimal: core Lean (always available in
 * the toolchain) plus `Std.Tactic.BVDecide` ONLY when a `bv_decide` theorem
 * is present. No Mathlib, no lakefile — the emitted file elaborates under
 * bare `lean --json <file>` with zero project scaffolding. Verified live on
 * this box (Lean 4.31.0, elan 4.2.3): `decide`, `omega`, and `grind` need no
 * import at all; `bv_decide` needs exactly `import Std.Tactic.BVDecide`,
 * which ships in core Std and needs no lake/Mathlib dependency
 * (research-lean4.md §1.1, §4 Tier L).
 *
 * This module is a pure string generator. It knows nothing about EARS,
 * requirements, or how a proposition was derived — callers (the Wave 2/3
 * encoder + certify runner) hand it already-valid Lean 4 proposition text
 * and a tactic choice; this module only handles batching, import dedupe,
 * and identifier hygiene so the emitted file is guaranteed to elaborate
 * syntactically (modulo the caller's own proposition being well-formed).
 */

/** The verified-sufficient core-Lean tactic subset (research-lean4.md §1.1, §4). */
export const LEAN_TACTICS = ['decide', 'omega', 'bv_decide', 'grind'] as const
export type LeanTactic = (typeof LEAN_TACTICS)[number]

/**
 * One theorem to emit into the batched file.
 *
 * `name` must already be a valid Lean 4 identifier — run arbitrary source
 * strings (e.g. requirement UUIDs) through {@link sanitizeLeanName} first.
 * `statement` is the caller-supplied Lean 4 proposition text (everything
 * that appears after the `:` and before `:= by`); it is emitted verbatim,
 * so callers own its correctness.
 */
export interface LeanTheoremSpec {
  /** Valid Lean 4 identifier, unique within the batched file. */
  name: string
  /** Lean 4 proposition text, e.g. `"∀ a b : Nat, a ≤ 10 → a + b ≥ 0"`. */
  statement: string
  /** Tactic that closes the `by` block. */
  tactic: LeanTactic
  /** Optional binder/hypothesis text inserted between the name and `:`, e.g. `"(a b : Nat) (h : a ≤ 10)"`. */
  binders?: string
}

export interface EmitLeanFileOptions {
  /** Optional extra `--` comment lines written above the import block (e.g. spec name/hash/timestamp). */
  headerComment?: readonly string[]
}

/** Import required by each tactic, or `undefined` if the tactic is available in core Lean with no import. */
const IMPORT_BY_TACTIC: Record<LeanTactic, string | undefined> = {
  decide: undefined,
  omega: undefined,
  grind: undefined,
  bv_decide: 'Std.Tactic.BVDecide',
}

const VALID_LEAN_IDENT = /^[A-Za-z_][A-Za-z0-9_']*$/

/**
 * Turn an arbitrary string (e.g. a requirement UUID like
 * `"7a1b2c3d-..."`) into a valid Lean 4 identifier: non-identifier
 * characters become `_`, and a leading digit gets an `_` prefix (Lean
 * identifiers cannot start with a digit). Deterministic and pure.
 */
export function sanitizeLeanName(raw: string): string {
  let s = raw.replace(/[^A-Za-z0-9_']/g, '_')
  if (s.length === 0 || /^[0-9]/.test(s)) {
    s = `_${s}`
  }
  return s
}

/**
 * Render a batched, self-contained `.lean` source file from a list of
 * theorem specs. Pure and deterministic: identical input always produces
 * an identical string. Throws if any `name` is not a valid Lean identifier
 * or if names collide (both would produce a file that fails to elaborate).
 */
export function emitLeanFile(
  theorems: readonly LeanTheoremSpec[],
  options: EmitLeanFileOptions = {},
): string {
  const seen = new Set<string>()
  for (const t of theorems) {
    if (!VALID_LEAN_IDENT.test(t.name)) {
      throw new Error(
        `emitLeanFile: theorem name "${t.name}" is not a valid Lean identifier — sanitize with sanitizeLeanName() first`,
      )
    }
    if (seen.has(t.name)) {
      throw new Error(`emitLeanFile: duplicate theorem name "${t.name}"`)
    }
    seen.add(t.name)
  }

  const imports = [
    ...new Set(
      theorems
        .map((t) => IMPORT_BY_TACTIC[t.tactic])
        .filter((imp): imp is string => imp !== undefined),
    ),
  ].sort()

  const lines: string[] = []
  lines.push('-- Generated by symspec certify. Core Lean only — no Mathlib, no lake.')
  if (options.headerComment) {
    for (const c of options.headerComment) {
      lines.push(`-- ${c}`)
    }
  }
  lines.push('')
  for (const imp of imports) {
    lines.push(`import ${imp}`)
  }
  if (imports.length > 0) {
    lines.push('')
  }

  for (const t of theorems) {
    const binders = t.binders ? ` ${t.binders}` : ''
    lines.push(`theorem ${t.name}${binders} : ${t.statement} := by`)
    lines.push(`  ${t.tactic}`)
    lines.push('')
  }

  return lines.join('\n').replace(/\n+$/, '\n')
}
